## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #E6FFFC
background               #0C1A19
selection_foreground     #0C1A19
selection_background     #40E0CF

cursor                   #9BF4EA
cursor_text_color        #0C1A19

url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

# black
color0   #0C1A19
color8   #5A7D79

# red
color1   #FF6B6B
color9   #FF8787

# green
color2   #00C2AD
color10  #68EADC

# yellow
color3   #E5C07B
color11  #FFD580

# blue
color4   #40E0CF
color12  #98F4E4

# magenta
color5   #C792EA
color13  #E9B7F3

# cyan
color6   #1CD3C0
color14  #40E0CF

# white
color7   #E6FFFC
color15  #FFFFFF

