# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME
font_family SpaceMono Nerd Font Mono
font_size 9.5
font_weight 500

#colores
foreground #E6FFFC
background #0C1A19



window_margin_width 0
window_padding_width 8

background_opacity 0.82
dynamic_background_opacity yes
background_blur 20


#cursor
cursor_shape block
cursor_blink_interval 0.75
cursor_stop_blinking_after 10.0

#urls
url_color #40E0CF
url_style curly
open_url_with default
detect_urls yes

#tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
tab_bar_margin_width 4
tab_bar_margin_height 4 0
tab_title_template " {title} "
active_tab_foreground   #0C1A19
active_tab_background   #40E0CF
active_tab_font_style   bold
inactive_tab_foreground #5A7D79
inactive_tab_background #0C1A19
tab_bar_background      #0C1A19

#paneles
map alt+left  neighboring_window left
map alt+right neighboring_window right
map alt+up    neighboring_window up
map alt+down  neighboring_window down

#limpio

enable_audio_bell no
inactive_text_alpha 0.90

