[opener]
edit = [
  { run = "nvim %s", block = true, for = "unix" }
]
open = [
  { run = "xdg-open %s", orphan = true, desc = "Open" }
]
image = [
  { run = "swayimg -e 'swayimg.viewer.set_default_scale(\"fit\")' %s", orphan = true }
]

[open]
prepend_rules = [
  { mime = "image/*", use = "image" },
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { mime = "application/toml", use = "edit" },
  { mime = "application/x-yaml", use = "edit" },
]
append_rules = [
  { mime = "*", use = "open" }
]
