ipc = on
splash = false

wallpaper {
  monitor = eDP-1
  path = /home/crasmerl/Descargas/background.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-4
  path = /home/crasmerl/Descargas/background.png
  fit_mode = cover
}

